<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Npgsql" Version="8.0.5" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../ETL.SPC.Application/ETL.SPC.Application.csproj" />
    <ProjectReference Include="../ETL.SPC.Domain/ETL.SPC.Domain.csproj" />
  </ItemGroup>

</Project>
